// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImportPolicy) DeepCopyInto(out *ImportPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImportPolicy.
func (in *ImportPolicy) DeepCopy() *ImportPolicy {
	if in == nil {
		return nil
	}
	out := new(ImportPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImportPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImportPolicyList) DeepCopyInto(out *ImportPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ImportPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImportPolicyList.
func (in *ImportPolicyList) DeepCopy() *ImportPolicyList {
	if in == nil {
		return nil
	}
	out := new(ImportPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImportPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImportPolicySpec) DeepCopyInto(out *ImportPolicySpec) {
	*out = *in
	in.ClusterSelector.DeepCopyInto(&out.ClusterSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImportPolicySpec.
func (in *ImportPolicySpec) DeepCopy() *ImportPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ImportPolicySpec)
	in.DeepCopyInto(out)
	return out
}
