/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	submarineriov1 "github.com/submariner-io/lighthouse/pkg/apis/submariner.io/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeImportPolicies implements ImportPolicyInterface
type FakeImportPolicies struct {
	Fake *FakeSubmarinerV1
	ns   string
}

var importpoliciesResource = schema.GroupVersionResource{Group: "submariner.io", Version: "v1", Resource: "importpolicies"}

var importpoliciesKind = schema.GroupVersionKind{Group: "submariner.io", Version: "v1", Kind: "ImportPolicy"}

// Get takes name of the importPolicy, and returns the corresponding importPolicy object, and an error if there is any.
func (c *FakeImportPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *submarineriov1.ImportPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(importpoliciesResource, c.ns, name), &submarineriov1.ImportPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*submarineriov1.ImportPolicy), err
}

// List takes label and field selectors, and returns the list of ImportPolicies that match those selectors.
func (c *FakeImportPolicies) List(ctx context.Context, opts v1.ListOptions) (result *submarineriov1.ImportPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(importpoliciesResource, importpoliciesKind, c.ns, opts), &submarineriov1.ImportPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &submarineriov1.ImportPolicyList{ListMeta: obj.(*submarineriov1.ImportPolicyList).ListMeta}
	for _, item := range obj.(*submarineriov1.ImportPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested importPolicies.
func (c *FakeImportPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(importpoliciesResource, c.ns, opts))

}

// Create takes the representation of a importPolicy and creates it.  Returns the server's representation of the importPolicy, and an error, if there is any.
func (c *FakeImportPolicies) Create(ctx context.Context, importPolicy *submarineriov1.ImportPolicy, opts v1.CreateOptions) (result *submarineriov1.ImportPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(importpoliciesResource, c.ns, importPolicy), &submarineriov1.ImportPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*submarineriov1.ImportPolicy), err
}

// Update takes the representation of a importPolicy and updates it. Returns the server's representation of the importPolicy, and an error, if there is any.
func (c *FakeImportPolicies) Update(ctx context.Context, importPolicy *submarineriov1.ImportPolicy, opts v1.UpdateOptions) (result *submarineriov1.ImportPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(importpoliciesResource, c.ns, importPolicy), &submarineriov1.ImportPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*submarineriov1.ImportPolicy), err
}

// Delete takes name of the importPolicy and deletes it. Returns an error if one occurs.
func (c *FakeImportPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(importpoliciesResource, c.ns, name), &submarineriov1.ImportPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeImportPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(importpoliciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &submarineriov1.ImportPolicyList{})
	return err
}

// Patch applies the patch and returns the patched importPolicy.
func (c *FakeImportPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *submarineriov1.ImportPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(importpoliciesResource, c.ns, name, pt, data, subresources...), &submarineriov1.ImportPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*submarineriov1.ImportPolicy), err
}
